### ISSUE TITLE
third-party cookies, certain trusted domains issue

### ISSUE THREAD

**Issue by DishantX** [atharva-lipare/MS-Teams-Auto-Joiner#3]
Google Browser sometimes stay in loop, and sometimes it does work.
Wish if it supported more web browsers- firefox, vivaldi

**Comment by atharva-lipare** [comment]
> Google Browser sometimes stay in loop, and sometimes it does work.

I didn't understand what you mean to say, could you clarify the issues you're facing?
> Wish if it supported more web browsers- firefox, vivaldi

Microsoft Teams doesn't support Firefox. I might add support for other chromium based browsers later.

**Comment by DishantX** [comment]
![image](https://user-images.githubusercontent.com/71291013/98641853-6e509f80-2352-11eb-9dbc-b05f47654d06.png)
Um
Sometimes it works after retrials of 3-4 times, and sometimes infinite loop

**Comment by DishantX** [comment]
lemme try if possible in Vivaldi (Chromium Based)

**Comment by DishantX** [comment]
I understood when the issue gets trigger

The script runs in command line since i converted into .exe but show issues(mentioned above) if i run by task scheduler.
